### ISSUE TITLE
index.html not found

### ISSUE THREAD

**Issue by rifkiaz** [pensiero/dockerfile-apache-php-mysql#1]
i have copied file index.html to /var/ww/html/ 

i run 
```
curl localhost
````
output is 404 not found.

**Comment by pensiero** [comment]
I'm not sure how you are using to run containers. Can you share that?
In any case, maybe a shot in the dark: have you tried with an `index.php` file?

**Comment by daf111** [comment]
I think that container document root is configured as /var/www/public
Try mapping this directory in your volumen.

**Comment by rifkiaz** [comment]
it's fixed for me right now. i'm config document root as /var/www/public
